### ISSUE TITLE
Suggestion: remove the ability to add spells to class, subclass, background, and backpack type items

### ISSUE THREAD

**Issue by krbz999** [ElfFriend-DnD/foundryvtt-items-with-spells-5e#1]
I feel like it makes little sense to have the ability to add them to these types. The first three already have 'Grant Items' advancements, and backpacks are backpacks.

A similar case might be able to be made for feature-type items, though that's debatable, and I can see a use for it there.

**Comment by akrigline** [comment]
Features I definitely will keep. I thought i removed the ability to add to Class items already. Forgot subclasses existed though. Those definitely should be disabled as there's not much use case for that in this.

Backpacks... I'm on the fence about. Probably will keep it. I could see for instance a "Bag of Hospitality" that's like a bag of holding but can cast magnificent mansion or the like. No need to implement a restriction like that.

**Comment by krbz999** [comment]
What about items already on the sheet - where spells cannot be added to them. If they have no spells, it would make for a cleaner UI to not display the additional tab.

**Comment by akrigline** [comment]
More interested in making it possible to add spells to those items, there's plenty of use case for that.

**Comment by krbz999** [comment]
A setting perhaps?

**Comment by akrigline** [comment]
come now, you know me better than that... i'll only put in a setting if its absolutely a problem :P

**Comment by krbz999** [comment]
Half the reason I ask is because I have to adjust my cursor movements to not click Effects on items cus they are where Details used to be now, due to the adjusted spacing. 😔

**Comment by SirMotte** [comment]
Please leave those functions in! Ever heard of cursed items, a backpack that makes everything it carries lighter. There are infinite possibilities on how to use this!

**Comment by akrigline** [comment]
1.2.0 Adds the ability to edit spells on owned items. I decided not to limit adding spells to any further item types simply because while not intended, nothing horrible will come about from it. But if I was to suddenly remove this ability it would be difficult to migrate users who are already doing this.
