### ISSUE TITLE
The Module isn't working anymore

### ISSUE THREAD

**Issue by spitfire1081** [ElfFriend-DnD/foundryvtt-items-with-spells-5e#12]
I used this module for some weeks.
It was working until yesterday, but now it is not listed in my modules anymore (it is listed as installed in the setup area, but won't appear in the client).
Some Screens:

![image](https://user-images.githubusercontent.com/12544098/214529782-17160555-f768-4e4a-8270-7da0ceef65e6.png)

![image](https://user-images.githubusercontent.com/12544098/214529947-4a49814c-d30f-4d30-9957-5392be68a13a.png)

![image](https://user-images.githubusercontent.com/12544098/214530001-66e0c70d-132c-4c8f-8a1a-a369f2b0dc22.png)

**Comment by akrigline** [comment]
What core foundry version and what dnd5e system version are you on?

**Comment by krbz999** [comment]
I've confirmed the module loads fine in a v2.1.2 world.
