### ISSUE TITLE
Multiple instances of each spell in Token Action HUD

### ISSUE THREAD

**Issue by Jefferydo** [ElfFriend-DnD/foundryvtt-items-with-spells-5e#13]
I created a magical item to hold all the wild magic and path of wild magic surge effects, which the player equips when surging to launch a particular spell. It's a staff with 18 spells on it. It causes multiple copies of each spell to show up in the Token Action HUD, beginning with 18 duplicates of Fire Bolt.

![staff-of-surging](https://user-images.githubusercontent.com/11779859/217999952-ecbc9007-cada-4d98-b800-0587d1d62c44.png)

![items-with-spells-token-action-HUD](https://user-images.githubusercontent.com/11779859/217999606-87fae0b3-de76-4fbd-ab0a-3929ca94de06.png)

**Comment by krbz999** [comment]
That's hilarious but clearly a bug on TAH's side, not IWS?

**Comment by Jefferydo** [comment]
Thanks, I'll post there.

**Comment by Jefferydo** [comment]
Update: When you delete a magic item holding spells from the character sheet, Items with Spells prompts if you want to delete the spells on the item as well. If you don't, the deleted item's spells persist in the Token Action HUD. 

Why are an item's spells a separate concern when deleting the item? Is there a use case for keeping a deleted item's spell list on the character?

**Comment by krbz999** [comment]
IMO, no deletion should ever be forced.

There is a key you can pass to the deletion to skip this prompt.

**Comment by akrigline** [comment]
The spells should also be appearing on the Character Actor Sheet's spellbook tab, under the "At Will" section IIRC.

The use case is mostly an opinion that that module should be relatively transparent in what it's doing. Those spells are part of the actor's spellcasting after the 'parent' item is added, the module simply provides a convienent way to organize said spells. But if the module were to malfunction or be disabled, the spells would still be there and would still function as well as Foundry supports spells on items normally.

In essence the opinion is:
> We are hesitant to make permanent destructive changes to an actor without the express consent of the user.

But as zhell mentioned, doing this deletion by API does provide an 'escape hatch' (mostly to help importers, but macros could make use of it as well). [Documentation](https://github.com/ElfFriend-DnD/foundryvtt-items-with-spells-5e#api)

**Comment by Jefferydo** [comment]
Ah, understood. You might want to consider a clearer prompt than "delete the spells from the item?", since the user just confirmed deletion of the item at the previous prompt. I interpreted it as delete the spells from the item in the sidebar, i.e., "you must hate the item, eh? Want to really kill it?" I don't know my way around the API yet so rather than edit the JSON I uninstalled and reinstalled Items w Spells to clear the spells from the HUD. 

This or something similar would be a lot clearer ... "Remove the item's spells from the character's spellbook?"

![image](https://user-images.githubusercontent.com/11779859/218891986-3fb82d9b-3df0-4236-8cdd-17dfbe8e3527.png)

**Comment by akrigline** [comment]
Ahhh that's a good call. worth a look at the prompt wording

**Comment by Jefferydo** [comment]
Folks on Discord are reporting duplicates in TA HUD. 

Can you please write a macro to clean the TA HUD of duplicates? To clear this, I have to uninstall and reinstall the Items w Spells module. 

![items-with-spells-token-action-HUD-2](https://user-images.githubusercontent.com/11779859/219968701-a6ddee7a-a42e-470a-b6ea-0bb1cf4614b7.png)

**Comment by krbz999** [comment]
How many instances of "Blinding Bolt" and "Drag Me To Hell" do you have on the character sheet?

**Comment by krbz999** [comment]
Nevermind. I followed the paper trail. This is definitely a TAH issue.

Context: TAH cannot render fast enough when multiple items are added, and supposedly they don't remove items from their HUD properly.
