### ISSUE TITLE
[Feature Request] Spells from module added in the bottom of the Spellbook

### ISSUE THREAD

**Issue by thatlonelybugbear** [ElfFriend-DnD/foundryvtt-items-with-spells-5e#4]
I was wondering if the spells added by an Item with spells, could be added after the rest of the spells, at the bottom by default.

![image](https://user-images.githubusercontent.com/7237090/200926807-2b39a077-5478-4c36-8e81-8d791fed093b.png)

**Comment by akrigline** [comment]
@krbz999 another of your beloved config options perhaps, I personally would not like this because of how long spell lists can get
