### ISSUE TITLE
Feature Request: Category bar charges

### ISSUE THREAD

**Issue by MotoMoto1234** [ElfFriend-DnD/foundryvtt-items-with-spells-5e#6]
When the staff of healing has X charges left, the spells are all under a category called Staff of Healing.  In that bar could it possibly show the charges on the origin magic item like X/Max.  
![image](https://user-images.githubusercontent.com/116308065/205947080-07b8f0c8-89ad-43a4-9b18-daa9dab20bed.png)

**Comment by akrigline** [comment]
This does happen normally, I'd guess tidy sheet is doing something to prevent our styling from appearing correctly.
